#!/bin/bash

echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<head>"
echo "<link rel="stylesheet" type="text/css" href="../stylesheets/stylesheet.css" />"
echo "<title>bWAPP - Уязвимость Shellshock</title>"
echo "</head>"
echo "<body>"
echo "<div id="frame">"
echo "<p>СОВЕТ: атакуйте заголовок реферера и вставьте этот флажок ...</p>"
echo "</div>"
echo "</body>"
echo "</html>"   